version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - WALLET_WWDR_CERT=${WALLET_WWDR_CERT}
      - WALLET_SIGNER_CERT=${WALLET_SIGNER_CERT}
      - WALLET_SIGNER_KEY=${WALLET_SIGNER_KEY}
      - WALLET_KEY_PASSPHRASE=${WALLET_KEY_PASSPHRASE}
      # Firebase configs
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID} 