version: '3.8'
services:
  api:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      # Wallet Pass Certificates
      - WALLET_WWDR_CERT=${WALLET_WWDR_CERT}
      - WALLET_SIGNER_CERT=${WALLET_SIGNER_CERT}
      - WALLET_SIGNER_KEY=${WALLET_SIGNER_KEY}
      - WALLET_KEY_PASSPHRASE=${WALLET_KEY_PASSPHRASE}
      # Firebase configs
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      # HERE Maps API Credentials
      - HERE_APP_ID=${HERE_APP_ID}
      - HERE_API_KEY=${HERE_API_KEY} 