@baseUrl = http://localhost:3000

### App Settings
GET {{baseUrl}}/app-settings

### App Settings by ID
GET {{baseUrl}}/app-settings/123

### Cities
GET {{baseUrl}}/cities

### Cities by ID
GET {{baseUrl}}/cities/123

### Chatrooms
GET {{baseUrl}}/cities/123/chatrooms


### Events
GET {{baseUrl}}/cities/123/events


### Messages
GET {{baseUrl}}/cities/123/chatrooms/456/messages


### Businesses
GET {{baseUrl}}/businesses

### Businesses by ID
GET {{baseUrl}}/businesses/123

### Business Categories
GET {{baseUrl}}/businesses/categories

### Business Users
GET {{baseUrl}}/businesses/users

### Users
GET {{baseUrl}}/users
GET {{baseUrl}}/users/123

### Users Profile
GET {{baseUrl}}/users/123/profile

POST {{baseUrl}}/users/123/profile
Content-Type: application/json

{
  "email": "test@example.com",
  "userType": "REGULAR",
  "managementId": "123"
}

PUT {{baseUrl}}/users/123/profile
Content-Type: application/json

{
  "name": "Test User",
  "language": "de"
}

DELETE {{baseUrl}}/users/123/profile

### Get Coupon Pass
GET {{baseUrl}}/wallet/coupon

### Get Personalized Pass
POST {{baseUrl}}/wallet/personalized/345
Content-Type: application/json

{
  "userId": "123",
  "userName": "John Doe",
  "memberSince": "2024-01"
} 